# DouYu.conf - 斗鱼去广告
# GitHub - MengZiJun0262
# Time - 2026-3-20

# 斗鱼广告接口-可能有问题
^https?:\/\/rtbapi\.douyucdn\.cn url reject-dict
# 斗鱼房间相关广告
^https?:\/\/apiv2\.douyucdn\.cn\/japi\/entrance\/roomRes\/.*\/m\/list url reject-dict
# 斗鱼首页推荐广告
^https?:\/\/apiv2\.douyucdn\.cn\/mgapi\/livenc\/home\/getRecV3 url script-response-body https://raw.githubusercontent.com/MengZiJun0262/NetWorkProxy/refs/heads/master/QuantumultX/JavaScript/DouYu.js
# 斗鱼鱼吧/关注页广告
^https?:\/\/apiv3\.douyucdn\.cn\/mgapi\/yubanc\/api\/feed\/followedUserFeedList\/v2 url script-response-body https://raw.githubusercontent.com/MengZiJun0262/NetWorkProxy/refs/heads/master/QuantumultX/JavaScript/DouYu.js

hostname = apiv2.douyucdn.cn, apiv3.douyucdn.cn, rtbapi.douyucdn.cn
