^https?:\/\/rtbapi\.douyucdn\.cn url reject-dict
^https?:\/\/apiv2\.douyucdn\.cn\/japi\/entrance\/roomRes\/.*\/m\/list url reject-dict
^https?:\/\/apiv[23]\.douyucdn\.cn\/mgapi\/.* url script-response-body https://raw.githubusercontent.com/MengZiJun0262/NetWorkProxy/refs/heads/master/QuantumultX/JavaScript/DouYu.js

hostname = apiv2.douyucdn.cn, apiv3.douyucdn.cn, rtbapi.douyucdn.cn
