^https?:\/\/rtbapi\.douyucdn\.cn url reject-dict
^https?:\/\/apiv[23]\.douyucdn\.cn\/mgapi\/.* url script-response-body DouYuHome.js
^https?:\/\/apiv2\.douyucdn\.cn\/japi\/entrance\/roomRes\/.*\/m\/list url reject-dict

hostname = apiv2.douyucdn.cn, apiv3.douyucdn.cn, rtbapi.douyucdn.cn
